name: assembly-synbio
description: This action asssembly sequences a list of DNA parts and create the final sequence with a composition of parts using the Golden Gate standard.
inputs:
    who-to-greet:  # id of input
        description: 'Who to greet'
        required: true
        default: 'World'
outputs:
    time: # id of output
    description: 'The time we greeted you'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.who-to-greet }}
author: Friendzymes Team
branding:
      icon: 'layers'
        color: 'purple'
